refactor: update README example screens
smart-village-solutions/smart-village-app-app pull request #1181
Opened 2024-08-19 10:57 UTC by d4v3d4vE

- took new screenshots and updated the image to keep it up to date

SVAI-12

## Screenshots:
![example-screens](https://github.com/user-attachments/assets/84ec93a9-f3ff-47b9-9fa9-3b49f640b514)

2024-08-19 11:03 UTC, ardasnturk commented
I prefer to use `assets/splash.png` instead of the first screenshot.

2024-08-19 11:09 UTC, donni106 commented on example-screens.png
thanks! two screens were questionable:

|1|2|
|---|---|
|![image](https://github.com/user-attachments/assets/da008dbc-4d36-487a-b3a4-c447bf111cd8)|![image](https://github.com/user-attachments/assets/19d5a8b9-eed3-4f7b-958a-59b831e37977)|

the contents are tooo dummy with weird texts, random images used for multiple places etc.
could you think of other screens showing those features? i guess the service panel screen can be found in different places with more useful content.
for the menu list you could create a new versioned static content that has all correct presentable entries, you know (e.g. no datenschutz and datenschutz2)?

2024-08-19 13:40 UTC, ardasnturk requested changes

2024-08-19 13:41 UTC, donni106 commented on example-screens.png
good point, it looks off with the rounded edges compared to the others.

2024-08-20 06:53 UTC, d4v3d4vE commented on example-screens.png
changed it to the `assets/splash.png`

2024-08-20 06:54 UTC, ardasnturk commented on example-screens.png
I don't find the DEVELOPMENT text in the first picture correct. Please get the splash screen from int/development branch in gitlab.

2024-08-20 06:56 UTC, d4v3d4vE commented on example-screens.png
couldn't find a better screen for screen 1 and for simple showcase purposes there should be no issue as long as we showcase that we have a widgets feature, what we do with that image

for the second screen I've photoshopped it based on your comment and removed all categories from "Über die App" which you didn't mention.

2024-08-20 07:21 UTC, donni106 commented on example-screens.png
it's ok arda, it is this file as you requested: https://github.com/smart-village-solutions/smart-village-app-app/blob/master/assets/splash.png
there is no int/dev here!

2024-08-20 07:22 UTC, donni106 approved these changes

2024-08-20 07:22 UTC, ardasnturk approved these changes

2024-08-20 07:23 UTC, donni106 commented on example-screens.png
:/ the screenshot in the description differs from the one in the code...there is no "DEVELOPMENT" on it...

2024-08-20 07:24 UTC, donni106 commented on example-screens.png
@d4v3d4vE i removed the screenshot from the description as it is not needed. the change show exactly the image and is better with direct comparison to the old one.
and: there is no need to invest time on manually changing the PR description at any time.

2024-08-20 07:24 UTC, merged

2024-08-20 07:27 UTC, donni106 commented on example-screens.png
a discussion does not mean to directly do stuff. it can be discussed first