fix: application crashing on the proposal creation screen for consul
smart-village-solutions/smart-village-app-app pull request #890
Opened 2023-08-04 17:52 UTC by ardasnturk

- updated the `expo-image-picker` package while updating the expo sdd and refactored the required
  fields that changed due to the update
  - for more detailed information please read the document: https://docs.expo.dev/versions/v48.0.0/sdk/imagepicker/#imagepickerlaunchimagelibraryasyncoptions
- removed privatisation for consul to remove complexity in `ImageSelector`
- replaced the `image` `defaultValues` in `NewPropsal` with an empty array since the customisation for consul has been removed and the application can run again
- renamed the `isVolunteer` prop to `isMultiImages` as only volunteer can select multiple images
- added `errorType` prop to `ImageSelector` component because different features have different error messages
- added `errorTextGenerator` function for generating error messages for volunteer and consul features
- added `errorMessage` to `Input` component to show image error messages in single image selectable features
- added text to show name, format and size information about the image
- changed the format of `newProposalData.image`, `JSON.parse` was used to access the uri of the image and the
  upload process to the server was updated with this uri
- added `containerStyle` and normalised `minHeight` value to fix the problem of multiline inputs overlapping with other inputs
- added `containerStyle` for different platforms after normalising the `minHeight` in the `NewDebate` componen because it is no longer needed.
- sorted `INPUT` array alphabetically

SVA-1098

***Error Texts***
---
**Consul**
|||||
|--|--|--|--|
![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-04 at 19 39 16](https://github.com/smart-village-solutions/smart-village-app-app/assets/11755668/99083911-715b-469d-87bd-a173b37c4af1)|![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-04 at 19 39 20](https://github.com/smart-village-solutions/smart-village-app-app/assets/11755668/bf66d450-5bd8-4bb2-9d59-64d8058f0a9d) | ![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-04 at 19 39 26](https://github.com/smart-village-solutions/smart-village-app-app/assets/11755668/d90b8dbd-2299-4ccb-b84c-d2b8eeff49a5) | ![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-04 at 19 39 32](https://github.com/smart-village-solutions/smart-village-app-app/assets/11755668/953b5e6e-5988-4efa-b174-9758412247e9)

**Mängelmelder**
||||
|--|--|--|
![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-04 at 19 41 29](https://github.com/smart-village-solutions/smart-village-app-app/assets/11755668/5ab4befa-70d8-4e50-9d2f-7faa866824df) | ![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-04 at 19 41 36](https://github.com/smart-village-solutions/smart-village-app-app/assets/11755668/365ad898-a4eb-45f1-b84c-3c7e1018eb29) |![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-04 at 19 41 42](https://github.com/smart-village-solutions/smart-village-app-app/assets/11755668/fc794ae2-e6c6-4e5a-ad7c-1028a8722ab3)

**Volunteer**
|||||
|--|--|--|--|
![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-04 at 19 43 14](https://github.com/smart-village-solutions/smart-village-app-app/assets/11755668/e878d2c1-6ec5-4a99-847f-50e889ae4e19)|![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-04 at 19 43 18](https://github.com/smart-village-solutions/smart-village-app-app/assets/11755668/62e30b4f-3c08-4d17-bf7e-dd7d005e582f)|![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-04 at 19 43 45](https://github.com/smart-village-solutions/smart-village-app-app/assets/11755668/a3ec1f9d-e287-491a-8731-ab62fecdb569)

2023-08-07 15:05 UTC, donni106 requested changes

2023-08-09 08:43 UTC, ardasnturk commented on src/hooks/imagePicker.ts
> +      return { uri: result.assets[0].uri, type: result.assets[0].type };
Yeah, you're right, I'll edit that. 👍

2023-08-09 08:43 UTC, ardasnturk commented on src/components/screens/consul/Proposals/NewProposal.js
> +      image: data?.image || '[]',
Because we parse the `defaultValue` in the `ImageSelector` component. If the `defaultValue` is not an array, we cannot parse it.

2023-08-09 08:43 UTC, ardasnturk commented on src/components/consul/selectors/ImageSelector.js
> +  const errorTextGenerator = async ({ uri, type }) => {
You are right. I can actually export the errorTextGenerator function as a helper.

2023-08-09 08:43 UTC, ardasnturk commented on src/components/consul/selectors/ImageSelector.js
> +      case 'volunteer':
Yeah, I'll do that. ✌️

2023-08-09 08:43 UTC, ardasnturk commented on src/components/consul/selectors/ImageSelector.js
> +    const consulErrorText = await imageErrorMessageGenerator(uri);
Yes, that's right. If I put them in the switch, the complexity in the code will be reduced a bit. 👍

2023-08-09 08:43 UTC, ardasnturk commented on src/components/consul/selectors/ImageSelector.js
> +          {!!infoAndErrorText?.[0]?.infoText && (
I'll try. 👍

2023-08-09 08:43 UTC, ardasnturk commented on src/components/screens/consul/Debates/NewDebate.js
> +    maxHeight: normalize(50),
Yes, that's right. I'll make it right. 👍

2023-08-09 08:44 UTC, ardasnturk commented on src/components/consul/selectors/ImageSelector.js
> +export const ImageSelector = ({ control, errorType, field, imageId, isMultiImages, item }) => {
I'm happy you like it. 🤝

2023-08-11 14:51 UTC, donni106 approved these changes

2023-08-11 14:51 UTC, merged