refactor: change query for index screen
smart-village-solutions/smart-village-app-app pull request #907
Opened 2023-08-23 14:12 UTC by ardasnturk

- replaced the `Query` component structure in `IndexScreen` with `useQuery` to use the `useFocusEffect` hook
- added the props used in `Query` to `useQuery`
- moved the functions, variables and controls used in the `Query` component above return to fix the problem of the `useIsFocused` hook being run continuously inside the `Query` component every time we open `IndexScreen`
- moved `fetchPolicy` variable above useQuery

SVA-1114

2023-08-24 08:16 UTC, d4v3d4vE approved these changes
Looks good to me!

2023-09-08 13:12 UTC, donni106 requested changes

2023-09-08 13:12 UTC, donni106 commented on src/screens/IndexScreen.js
sadly I have duplicated events in calendar view on a date.

![Simulator Screen Shot - iPhone 12 - 2023-09-08 at 15 10 40-tile](https://github.com/smart-village-solutions/smart-village-app-app/assets/1942953/28748f71-ef7a-4de6-8810-7857590749b8)

I will look deeper into it.

2023-09-08 13:14 UTC, donni106 commented on src/screens/IndexScreen.js
and after pull to refresh I have some entries of earlier days visible

![Simulator Screen Shot - iPhone 12 - 2023-09-08 at 15 14 12](https://github.com/smart-village-solutions/smart-village-app-app/assets/1942953/06a6d8b2-1655-4162-842d-9b92af470a29)

2023-09-08 13:23 UTC, donni106 commented on src/screens/IndexScreen.js
and sometimes the last entry is duplicated

![Simulator Screen Shot - iPhone 12 - 2023-09-08 at 15 22 14-tile](https://github.com/smart-village-solutions/smart-village-app-app/assets/1942953/23dbec87-c61c-4447-846c-2e0eb72273ff)

2023-09-08 13:49 UTC, donni106 commented on src/screens/IndexScreen.js
> +                onRefresh={() => refresh(refetch)}
as `refetch` comes from hook `const { data, loading, fetchMore, refetch } = useQuery(` now, we do not need to pass it to the `refresh` method, at is already defined.

2023-10-05 08:25 UTC, donni106 commented on src/screens/IndexScreen.js
refactoring done

2023-10-05 08:25 UTC, closed without merging