feat(sue): make api connections
smart-village-solutions/smart-village-app-app pull request #959
Opened 2023-10-25 15:42 UTC by ardasnturk

- added queries, hooks and types required to connect to open311 api

SUE-2

2023-10-26 15:58 UTC, donni106 requested changes

2023-10-26 20:49 UTC, ardasnturk commented on src/queries/SUE/requestsWithServiceRequestId.tsx
> +      accept: 'application/json;charset=UTF-8',
No, it's not necessary. I overlooked that. I'll change it.

2023-10-26 20:49 UTC, ardasnturk commented on src/helpers/sueHelper.ts
> +const mandantenId = secrets[namespace]?.sue?.mandantenId;
You are absolutely right! I'll change it. 👍

2023-10-26 20:51 UTC, ardasnturk commented on src/helpers/sueHelper.ts
> +export const sueApiUrl = secrets[namespace]?.sue?.serverUrl;
Yes, that's right. It can be called serverUrl. It is important for the integrity of the code. 🤝

2023-10-26 20:52 UTC, ardasnturk commented on src/helpers/parser/listItemParser.js
> +
Yes we can. 💪😁

2023-10-27 12:49 UTC, ardasnturk commented on src/hooks/SUE/data.ts
> +  const [sueData, setSUEData] = useState<any[]>([]);
https://github.com/smart-village-solutions/smart-village-app-app/pull/959/commits/e972ae4e3b99d731e5307e64f389295212c1d808

2023-10-27 12:49 UTC, ardasnturk commented on src/helpers/parser/listItemParser.js
> +      updatedDate: item?.updated_datetime,
https://github.com/smart-village-solutions/smart-village-app-app/pull/959/commits/e972ae4e3b99d731e5307e64f389295212c1d808

2023-10-27 12:49 UTC, ardasnturk commented on src/hooks/SUE/data.ts
> +export const useSUEData = ({
https://github.com/smart-village-solutions/smart-village-app-app/pull/959/commits/e972ae4e3b99d731e5307e64f389295212c1d808

2023-10-27 12:49 UTC, ardasnturk commented on src/hooks/SUE/data.ts
> +  }, [processUSEData]);
https://github.com/smart-village-solutions/smart-village-app-app/pull/959/commits/e972ae4e3b99d731e5307e64f389295212c1d808

2023-10-27 12:50 UTC, ardasnturk commented on src/hooks/SUE/data.ts
> +    let processedUSEData = data as any[];
https://github.com/smart-village-solutions/smart-village-app-app/pull/959/commits/e972ae4e3b99d731e5307e64f389295212c1d808

2023-10-27 12:50 UTC, ardasnturk commented on src/helpers/sueHelper.ts
> +export const sueRequestsUrl = `${sueApiUrl}/requests?jurisdiction_id=${mandantenId}`;
https://github.com/smart-village-solutions/smart-village-app-app/pull/959/commits/e972ae4e3b99d731e5307e64f389295212c1d808

2023-10-27 12:50 UTC, ardasnturk commented on src/queries/SUE/requestsWithServiceRequestId.tsx
> +      accept: 'application/json;charset=UTF-8',
https://github.com/smart-village-solutions/smart-village-app-app/pull/959/commits/e972ae4e3b99d731e5307e64f389295212c1d808

2023-10-27 12:50 UTC, ardasnturk commented on src/helpers/sueHelper.ts
> +export const sueApiUrl = secrets[namespace]?.sue?.serverUrl;
https://github.com/smart-village-solutions/smart-village-app-app/pull/959/commits/e972ae4e3b99d731e5307e64f389295212c1d808

2023-10-27 12:50 UTC, ardasnturk commented on src/helpers/sueHelper.ts
> +export const sueApiKey = secrets[namespace]?.sue?.apiKey;
https://github.com/smart-village-solutions/smart-village-app-app/pull/959/commits/e972ae4e3b99d731e5307e64f389295212c1d808

2023-10-27 12:50 UTC, ardasnturk commented on src/helpers/parser/listItemParser.js
> +      requestedDate: item?.requested_datetime,
https://github.com/smart-village-solutions/smart-village-app-app/pull/959/commits/cb9aba34c1d0444db590dfab0c074fc8676d461c

2023-10-27 12:51 UTC, ardasnturk commented on src/helpers/parser/listItemParser.js
> +
https://github.com/smart-village-solutions/smart-village-app-app/pull/959/commits/cb9aba34c1d0444db590dfab0c074fc8676d461c

2023-10-27 12:51 UTC, ardasnturk commented on src/helpers/parser/listItemParser.js
> +      return parseSUEStatuses(data);
https://github.com/smart-village-solutions/smart-village-app-app/pull/959/commits/cb9aba34c1d0444db590dfab0c074fc8676d461c

2023-10-27 12:51 UTC, ardasnturk commented on src/helpers/index.js
https://github.com/smart-village-solutions/smart-village-app-app/pull/959/commits/cb9aba34c1d0444db590dfab0c074fc8676d461c

2023-10-27 12:52 UTC, ardasnturk commented on src/helpers/parser/listItemParser.js
> +      picture: { url: mainImageOfMediaContents(parsedMediaUrl) },
I will respond to this comment after looking at the PR created for DetailScreen. I don't know exactly what needs to be done at the moment.

2023-11-01 16:18 UTC, donni106 approved these changes

2023-11-01 16:18 UTC, donni106 commented on src/helpers/parser/listItemParser.js
> +      picture: { url: mainImageOfMediaContents(parsedMediaUrl) },
Is refactored

2023-11-01 17:40 UTC, merged